name: opera-change
channels:
 - conda-forge
dependencies:
 - python
 - jupyter
 - rasterio
 - shapely
 - numpy
 - matplotlib
 - fiona
 - geopandas
 - tqdm
 - pip
 - notebook
 - jupyterlab
 - pytest
 - contextily
 - scikit-image
 - scikit-learn
 - asf_search
 - flake8
 - flake8-blind-except
 - flake8-builtins
 - flake8-import-order
 - pystac-client
 - astropy
 - dem_stitcher
 - pip:
   - git+https://github.com/ACCESS-Cloud-Based-InSAR/dem-stitcher.git@performance-improvement
   - git+https://github.com/OPERA-Cal-Val/tile-stitcher